version: '3.8'

services:
  flaskapp:
    build: .
    ports:
      - "80:80"
    environment:
      - MONGO_URI=mongodb://mongo-bgdb:27017/bgdb
      - FLASK_APP=app.py
    depends_on:
      - mongo-bgdb
    container_name: bgdb

  mongo-bgdb:
    image: mongo:latest
    container_name: mongo-bgdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
