version: '3.8'

services:
  flaskapp:
    build: .
    ports:
      - "80:80"
    environment:
      - MONGO_URI=mongodb://mongo-bgdb:27017/bgdb
      - FLASK_APP=app.py
    depends_on:
      - mongo-bgdb
    container_name: bgdb

  mongo-bgdb:
    image: mongo:latest
    container_name: mongo-bgdb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    #para generar un backup en formato json ejecutar este comando:
    #docker exec -it mongo-bgdb mongoexport --db=bgdb --collection=items --out=/data/db/backup.json --jsonArray

volumes:
  mongo-data:
